module.exports = {
  ROLES: {
    ADMIN: 'ADMIN',
    COORDINADOR: 'COORDINADOR',
    LIDER: 'LIDER'
  },

  ESTADO_CONTACTO: {
    CONFIRMADO: 'CONFIRMADO',
    CONTACTADO: 'CONTACTADO',
    PENDIENTE: 'PENDIENTE',
    NO_CONTACTADO: 'NO_CONTACTADO'
  },

  ESTADO_RPA: {
    NUEVO: 'NUEVO',
    PENDIENTE_CONSULTA: 'PENDIENTE_CONSULTA',
    CONSULTANDO: 'CONSULTANDO',
    ACTUALIZADO: 'ACTUALIZADO',
    ERROR_CONSULTA: 'ERROR_CONSULTA',
    PENDIENTE_ACTUALIZACION: 'PENDIENTE_ACTUALIZACION'
  },

  PRIORIDAD: {
    ALTA: 1,
    MEDIA: 2,
    BAJA: 3
  }
};